version: '3'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - db
    command: yarn test
    networks:
      - app-connect
    ports:
      - '3333:3333'

  db:
    image: 'mongo'
    container_name: MONGO_DB
    volumes:
      - mongodb-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

volumes:
  mongodb-data:

networks:
  app-connect:
      driver: bridge